test_pod:
  enabled: true
  image: bats/bats:1.8.2
  pullPolicy: IfNotPresent

loki:
  enabled: true
  isDefault: true
  url: http://loki:3100
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  datasource:
    jsonData: "{}"
    uid: ""
    


promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://{{ .Release.Name }}:3100/loki/api/v1/push
    snippets:
      scrapeConfigs: |
        - job_name: kubernetes-pods-restapi-student-api
          pipeline_stages:
            - cri: {}
            - match:
                selector: '{app="restapi", namespace="student-api"}'
                stages:
                  # Pattern 1: JSON logs (Python application logs)
                  - json:
                      expressions:
                        timestamp: timestamp
                        level: level
                        message: message
                        function: function
                        line: line
                        file: file
                        module: module
                  - json:
                      source: message
                      expressions:
                        event: event
                        endpoint: endpoint
                  # Pattern 2: HTTP logs
                  - regex:
                      expression: '(?P<level>\w+):\s+(?P<client_ip>[\d\.]+):(?P<client_port>\d+) - "(?P<http_method>[A-Z]+) (?P<endpoint>[^ ]+) HTTP/\d\.\d" (?P<status_code>\d+) (?P<status_message>.*)'
                  # Set labels for all parsed fields
                  - labels:
                      timestamp:
                      level:
                      module:
                      function:
                      line:
                      file:
                      event:
                      endpoint:
                      http_method:
                      client_ip:
                      status_code:
                      status_message:
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            # Filter by namespace - keep only student-api namespace
            - source_labels:
                - __meta_kubernetes_namespace
              action: keep
              regex: student-api
            # Filter by app - keep only restapi app
            - source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
                - __meta_kubernetes_pod_label_app
              regex: restapi|;restapi|restapi;.*
              action: keep
            # Setup app label properly
            - source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
                - __meta_kubernetes_pod_label_app
                - __meta_kubernetes_pod_name
              regex: ^;*([^;]+)(;.*)?$
              action: replace
              target_label: app
            # Keep essential labels only
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_node_name
              target_label: node_name
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              replacement: $1
              separator: /
              source_labels:
              - namespace
              - app
              target_label: job
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_container_name
              target_label: container
            # Set up proper path to logs
            - action: replace
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
              target_label: __path__
            - action: replace
              regex: true/(.*)
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
              - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
              - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
              - __meta_kubernetes_pod_container_name
              target_label: __path__

fluent-bit:
  enabled: false

grafana:
  enabled: true
  persistence:
    enabled: true
    size: 5Gi
  

  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
    alerts:
      enabled: true
      label: grafana_alert
      labelValue: "1"
      searchNamespace: ALL

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus:9090/  
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki:3100 # Update with your actual Loki service name and port
        access: proxy

  image:
    tag: 10.3.3


  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards
  
prometheus:
  enabled: false

filebeat:
  enabled: false

logstash:
  enabled: false


proxy:
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
